## 202331291_Rafi Indra Pramudhito Zuhayr

### Import library

In [1]:
import cv2
import numpy as np

### Membaca Citra

In [3]:
citra = cv2.imread("image.webp")
cv2.imshow("Original", citra)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Dimensi Citra

In [4]:
print(citra.shape)
print(citra.dtype)

(1067, 1600, 3)
uint8


In [5]:
print(citra)

[[[216 225 205]
  [216 225 205]
  [216 225 205]
  ...
  [ 15  77  33]
  [ 18  81  37]
  [ 26  89  45]]

 [[213 222 203]
  [213 222 203]
  [213 222 203]
  ...
  [  0  60  16]
  [  1  64  19]
  [  9  72  27]]

 [[209 218 198]
  [209 218 198]
  [209 218 198]
  ...
  [  0  60  16]
  [  1  64  19]
  [  9  72  27]]

 ...

 [[191 203 187]
  [191 203 187]
  [191 203 187]
  ...
  [126 150 125]
  [128 152 128]
  [130 154 130]]

 [[191 203 187]
  [191 203 187]
  [191 203 187]
  ...
  [126 150 125]
  [128 152 128]
  [130 154 130]]

 [[192 204 188]
  [192 204 188]
  [192 204 188]
  ...
  [128 152 128]
  [130 154 130]
  [133 157 132]]]


### Splitting Citra RGB

In [6]:

b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]

In [7]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]
        
citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:

print(citra_gray)

[[217 217 217 ...  56  60  68]
 [215 215 215 ...  40  43  51]
 [210 210 210 ...  40  43  51]
 ...
 [196 196 196 ... 139 142 144]
 [196 196 196 ... 139 142 144]
 [197 197 197 ... 142 144 146]]


### Grayscale to Binary

In [9]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray [i,j] >= ambang:
            citra_biner[i,j] = 1
        else:
            citra_biner[i,j] = 0

cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:

print(citra_biner)

[[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
